// Generated by postgres-meta v0.99.0 from the manual issuance migrations applied to isolated PostgreSQL 17.
// Reduced by scripts/extract-manual-reco-types.mjs; do not edit DB shapes by hand.
export type Json = string | number | boolean | null | {
    [key: string]: Json | undefined;
} | Json[];
export type Database = {
    public: {
        Tables: {
            reco_manual_operations: {
                Row: {
                    actor_id: string;
                    also_sms: boolean;
                    created_at: string;
                    id: string;
                    member_id: string;
                    reason: string | null;
                    round_no: number;
                    set_count: number;
                    status: string;
                };
                Insert: {
                    actor_id: string;
                    also_sms: boolean;
                    created_at?: string;
                    id: string;
                    member_id: string;
                    reason?: string | null;
                    round_no: number;
                    set_count: number;
                    status: string;
                };
                Update: {
                    actor_id?: string;
                    also_sms?: boolean;
                    created_at?: string;
                    id?: string;
                    member_id?: string;
                    reason?: string | null;
                    round_no?: number;
                    set_count?: number;
                    status?: string;
                };
                Relationships: [
                ];
            };
            reco_issue_ledger: {
                Row: {
                    actor_id: string | null;
                    claim_token: string;
                    created_at: string;
                    finished_at: string | null;
                    id: string;
                    issue: Json;
                    manual_request_id: string | null;
                    member_id: string;
                    mode: string;
                    phone: string;
                    receipt: Json | null;
                    round_no: number;
                    should_send: boolean;
                    source_site: string;
                    status: string;
                };
                Insert: {
                    actor_id?: string | null;
                    claim_token?: string;
                    created_at?: string;
                    finished_at?: string | null;
                    id?: string;
                    issue: Json;
                    manual_request_id?: string | null;
                    member_id: string;
                    mode: string;
                    phone?: string;
                    receipt?: Json | null;
                    round_no: number;
                    should_send: boolean;
                    source_site: string;
                    status?: string;
                };
                Update: {
                    actor_id?: string | null;
                    claim_token?: string;
                    created_at?: string;
                    finished_at?: string | null;
                    id?: string;
                    issue?: Json;
                    manual_request_id?: string | null;
                    member_id?: string;
                    mode?: string;
                    phone?: string;
                    receipt?: Json | null;
                    round_no?: number;
                    should_send?: boolean;
                    source_site?: string;
                    status?: string;
                };
                Relationships: [
                ];
            };
            member_reco_reset_archive: {
                Row: {
                    issues: Json;
                    member_id: string;
                    operation_id: string;
                    reset_at: string;
                    reset_by: string;
                };
                Insert: {
                    issues: Json;
                    member_id: string;
                    operation_id: string;
                    reset_at: string;
                    reset_by: string;
                };
                Update: {
                    issues?: Json;
                    member_id?: string;
                    operation_id?: string;
                    reset_at?: string;
                    reset_by?: string;
                };
                Relationships: [
                ];
            };
        };
        Functions: {
            reco_issue_manual_claim: {
                Args: {
                    p_actor?: string;
                    p_also_sms?: boolean;
                    p_expected_grade?: string;
                    p_expected_meta: Json;
                    p_expected_phone?: string;
                    p_expected_site: string;
                    p_issue: Json;
                    p_member_id: string;
                    p_mode?: string;
                    p_operation_id: string;
                    p_round_no: number;
                    p_set_count?: number;
                    p_today: string;
                    p_weekday: number;
                };
                Returns: Json;
            };
            reco_manual_block: {
                Args: {
                    p_operation_id: string;
                    p_reason: string;
                };
                Returns: Json;
            };
            admin_delete_member_reco: {
                Args: {
                    p_issued_at: string;
                    p_member_id: string;
                    p_round_no: number;
                };
                Returns: Json;
            };
        };
    };
};
