// Generated by postgres-meta v0.99.0 from the reset migration applied to isolated PostgreSQL 17.
// Reduced by scripts/extract-member-reset-types.mjs; do not edit DB shapes by hand.
export type Json = string | number | boolean | null | {
    [key: string]: Json | undefined;
} | Json[];
export type Database = {
    public: {
        Tables: {
            member_reco_reset_archive: {
                Row: {
                    issues: Json;
                    member_id: string;
                    operation_id: string;
                    reset_at: string;
                    reset_by: string;
                };
                Insert: {
                    issues: Json;
                    member_id: string;
                    operation_id: string;
                    reset_at: string;
                    reset_by: string;
                };
                Update: {
                    issues?: Json;
                    member_id?: string;
                    operation_id?: string;
                    reset_at?: string;
                    reset_by?: string;
                };
                Relationships: [
                ];
            };
            member_reset_receipts: {
                Row: {
                    actor_id: string;
                    created_at: string;
                    member_ids: string[];
                    operation_id: string;
                };
                Insert: {
                    actor_id: string;
                    created_at: string;
                    member_ids: string[];
                    operation_id: string;
                };
                Update: {
                    actor_id?: string;
                    created_at?: string;
                    member_ids?: string[];
                    operation_id?: string;
                };
                Relationships: [
                ];
            };
        };
        Functions: {
            admin_reset_members: {
                Args: {
                    p_member_ids: string[];
                    p_operation_id: string;
                };
                Returns: Json;
            };
        };
    };
};
