-- admin_member_search 를 매 호출 다시 계획하게 한다 (현장 9/11 "검색 속도가 매우 느립니다").
--
-- 20260911020000 에서 전화번호 조건을 LIKE 로 되돌려 trigram 인덱스는 되살렸지만,
-- 그것만으로는 부족했다. 남은 절반이 이것이다.
--
-- 무슨 일이 일어나는가
--   20260909001521 이 조회 RPC를 LANGUAGE sql → plpgsql 로 바꿨다. plpgsql 은 같은 문장을
--   5회 실행한 뒤 generic plan(인자값을 모르는 계획)으로 굳힐 수 있다. 검색은 인자값에 따라
--   최적 경로가 완전히 달라지는데, 한 번 굳은 계획이 이후 모든 검색어에 그대로 쓰인다.
--   `(v_source_site IS NULL OR ...)` 의 IS NULL 가지도 generic plan 에서는 접히지 않아
--   사이트 조건을 인덱스 조건으로 만들 수 없다.
--
-- 왜 이 함수만인가
--   admin_members_page(회원목록)는 `total` 을 위해 전체 건수를 세므로, 플래너가 어차피
--   trigram 비트맵 경로를 골라야 해서 계획이 흔들리지 않는다(실측 5.8ms vs 4.7ms — 차이 없음).
--   admin_member_search 는 `order by ... limit 20` 뿐이라 조기 종료 경로를 노릴 여지가 있고,
--   굳은 계획이 그 잘못된 길을 계속 고른다.
--
-- 실측 (PG16 · 회원 450,000 · 서로 다른 검색어 10개를 차례로 — 현장의 실제 사용 패턴)
--   기본계획      : 평균 243.8 ms / 최악 719.3 ms
--   force_custom  : 평균   2.4 ms / 최악   4.3 ms
--
-- 앞선 판단 정정
--   이 가설을 한 번 세웠다가 "차이 없음"으로 버린 적이 있다(2.7ms vs 2.5ms). 그 측정은
--   **같은 검색어를 10번 반복**한 것이라 generic plan 문제가 드러나지 않는 조건이었다.
--   검색어를 매번 바꾸자(=현장 사용 패턴) 100배 차이가 났다. 재현 조건이 틀리면
--   맞는 가설도 기각된다.
--
-- 비용: 호출마다 계획을 다시 세우므로 1ms 안팎이 더 든다. 위 수치에 이미 포함돼 있다.

ALTER FUNCTION public.admin_member_search(text, integer, text)
  SET plan_cache_mode = 'force_custom_plan';
